site_name: From Data Processing Algorithm to Production: Guidelines for Designing and Preparing Data Processing Chains
site_description: This guide compiles best practices and expectations for the design and development phase of a data processing chain, ensuring its optimal use for deployment in a data production center or similar facility. The ecosystem surrounding information technologies used for Earth observation is becoming increasingly standardized through consortia like the OGC and standards like STAC, supported by the ESA. There are also dynamics surrounding Cloud Compliant standards, such as those developed by the CNG. Adhering to these standards enhances the visibility of the chains that reference them and thus provides significant support for the dissemination of the algorithms used.
site_author: CNES
site_url: https://cnes.fr
nav:
  - Home: index.md
  - Best Practices: best_practices.md
  - Data Processing Chain Template: Data_processing_chain_template.md
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
